auth_enabled: false

server:
  http_listen_port: 3100

distributor:
  receivers:
    otlp:
      protocols:
        http:
        grpc:

ingester:
  trace_idle_period: 10s
  max_block_bytes: 1_000_000
  max_block_duration: 5m

compactor:
  compaction:
    compaction_window: 1h
    max_block_bytes: 100_000_000
    block_retention: 1h
    compacted_block_retention: 10m

storage:
  trace:
    backend: local
    block:
      bloom_filter_false_positive: .05
      # index_downsample_bytes: 1000
      # encoding: zstd
    wal:
      path: /tmp/tempo/wal
      # encoding: none
    local:
      path: /tmp/tempo/blocks
    pool:
      max_workers: 100
      queue_depth: 1000

# Metrics-generator configuration block
metrics_generator:
  processor:
    service_graphs:
      wait: 10s
      max_items: 10000
      workers: 10
    span_metrics:
      enable_target_info: true
  registry:
    collection_interval: 10s
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      - url: http://monitoring-prometheus:9090/api/v1/write
        send_exemplars: true
  metrics_ingestion_time_range_slack: 30s

overrides:
  metrics_generator_processors:
    - service-graphs
    - span-metrics
